location = "local-1"
server_id = 1
num_clients = 1
listen_address = "127.0.0.1"
listen_port = 8001
output_filepath = "./logs/clock-benchmark/low/server-1.json"

[clock]
node_id = 1
drift_rate_us_per_sec = 2000
sync_uncertainty_us = 1000
sync_period_us = 100000
seed = 42
